name: Build RFC

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Compile draft or RFC
      run: |
        mkdir -p build
        for file in draft-*.xml; do
            xml2rfc --text --html -b build $file
        done
    - name: Store artifacts
      uses: actions/upload-artifact@v4
      with:
        name: draft-ietf-netconf-privcand
        path: |
          build/*.txt
          build/*.html
        retention-days: 5
    - name: Output git status
      run: git status
    - name: Download artifacts
      uses: actions/download-artifact@v4
    - name: stage changed files
      run: git add .
    - name: Add username
      run: git config user.name $env:GITHUB_TRIGGERING_ACTOR
    - name: Commit changed files
      run: git commit -m "Auto updating txt and html versions of the draft"
        

