name: Build draft in XML and TXT on commit

on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install xml2rfc
      run: apt-get install -y xml2rfc
    - uses: actions/checkout@v4
    - name: Run a one-line script
      run: ./build-all.sh
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    # - name: stage changed files
    #   run: git add .
    # - name: commit changed files
    #   run: git commit -m "Auto updating compiled draft revisions"
    # - name: fetch from master
    #   run: git fetch origin master
    # - name: push code to master
    #   run: git push origin HEAD:master